import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Assignment',
  description: 'Generated by Next.js',
}

import Navbar from '@/components/Navbar';
import { NavigationProvider } from '@/contexts/NavigationContext';
import NavigationLoading from '@/components/NavigationLoading';
import NavigationEndHandler from '@/components/NavigationEndHandler';
import Footer from '@/components/Footer';
import TopLoader from '@/components/TopLoader';
import PerformanceOptimizer from '@/components/PerformanceOptimizer';
import { AuthProvider } from '@/contexts/AuthContext';
import { CartProvider } from '@/contexts/CartContext';
import { ToastProvider } from '@/contexts/ToastContext';
import { ToastContainer } from '@/components/Toast';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ToastProvider>
            <CartProvider>
              <NavigationProvider>
                <PerformanceOptimizer>
                  <TopLoader />
                  <NavigationLoading delay={0} minDuration={160} />
                  <Navbar />
                  <main className="pt-0"> 
                    {children}
                  </main>
                  <Footer />
                  <ToastContainer />
                  <NavigationEndHandler />
                </PerformanceOptimizer>
              </NavigationProvider>
            </CartProvider>
          </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  )
}