import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Assignment',
  description: 'Generated by Next.js',
}

import Navbar from '@/components/Navbar';


import Footer from '@/components/Footer';
import TopLoader from '@/components/TopLoader';

import { AuthProvider } from '@/contexts/AuthContext';
import { CartProvider } from '@/contexts/CartContext';
import { ToastProvider } from '@/contexts/ToastContext';
import { ToastContainer } from '@/components/Toast';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ToastProvider>
            <CartProvider>
              <TopLoader />
              <Navbar />
              <main className="pt-0"> 
                {children}
              </main>
              <Footer />
              <ToastContainer />
            </CartProvider>
          </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  )
}